### PR TITLE
Updated for Swift 2.2

### PR DESCRIPTION
**Pull request by scottbyrns**

### CODE REVIEW

**Comment by czechboy0** [comment]
Hi @scottbyrns,

thanks for taking the time to do the upgrade to Swift 3, however I needed to do a couple of more changes (in tests in particular), so I did the work in #16. :blush: Now it's merged so `master` is Swift 3 compatible - hopefully exactly what you needed.

**Comment by scottbyrns** [comment]
That was exactly what I needed. When you say swift 3 what are you meaning exactly? I thought I was on swift 2.2 when I made these changes. We made roughly the same changes and your 0.1.0 release was interchangeable with the 0.0.4 release I did on my fork. I'm just getting started developing libraries in swift on linux so I'm not really sure what all is what yet.

**Comment by czechboy0** [comment]
Yeah the changes I made were for Swift 3. Previously it was 2.2 compatible, but there were source breaking changes in 3.

**Comment by scottbyrns** [comment]
Maybe I've been building against 3 over here. I pulled the latest dev builds from swift.org to work from. Your changes compiled into my project with no issues and 2.2 code hasn't been compiling always for my local environment.

**Comment by czechboy0** [comment]
So here: https://swift.org/download/#releases the Releases section at the top is Swift 2.2, and the master snapshots are of Swift 3. The changes I made above are definitely for Swift 3 (those were the changes to make the APIs more Swift-y, usually less verbose).

**Pull request closed without merging**
