### PR TITLE
Implement client-side support for sockets being closed gracefully by the server

### PR DESCRIPTION
**Pull request by Joannis**
Fixing #91

### CODE REVIEW

**Comment by andreasley** [comment]
Good catch. I think throwing an error is not appropriate here. Maybe something like this instead:

```swift
if receivedBytes == 0 && maxBytes != 0 {
    // A return value of 0 indicates that the remote peer has performed an orderly shutdown.
    // In this case, this socket can be closed.
    try self.close()
    return Array()
}
```

Not sure yet if `Engine` or `Vapor` need adjustments for that to ensure everything is cleaned up properly.

**Comment by Joannis** [comment]
I think `try self.close()` will throw too since I think you can't close a closed socket.

**Comment by andreasley** [comment]
True, but the error thrown from calling `close()` a second time is ignored in `Engine` and won't show up in the log (as opposed to when throwing from `recv`).
Also, `Engine` only closes the socket if the parser detects an empty stream, which it never will if `recv` throws, so the connection continues to exist. Of course this could all be changed, but in my opinion, `Engine` shouldn't have to worry about socket details anyway.

**Comment by Joannis** [comment]
I'm not sure if `Engine` should be the main perspective here. I'm pretty sure there are many other libraries running socks, like MongoKitten for example, which are also suffering from closed connections.

**Comment by andreasley** [comment]
I agree.

Still: Is it appropriate to throw an error if the remote peer performed an orderly shutdown?

**Comment by Joannis** [comment]
Does anyone else care to weigh in? @LoganWright @tannernelson maybe?

**Comment by LoganWright** [comment]
Are there alternatives that 

1. don't throw
2. still close properly in socks for dependent libs.

**Comment by Joannis** [comment]
Is it normal that the WatchingTests fail?

**Comment by andreasley** [comment]
@Joannis Not really. They used to work, but something (in Travis?) changed and I couldn't reproduce the error yet. :(

**Review by loganwright — APPROVED** [review]

**Comment by LoganWright** [comment]
@tannernelson @andreasley @Joannis this looks good to me, any last comments before I merge it?

**Comment by andreasley** [comment]
@LoganWright Maybe add a comment why the socket should be closed if we get a return value of 0 (see my first comment)? That's all. :)

Note: We'll have to update `Engine` slightly.

**Pull request merged**
